package com.practice.expenseAssistant.utils

enum class ExpenseType(val value: String) {
    OTHERS("Others"),
    BILL("Bill"),
    BABY("Baby"),
    CLOTHING("Clothing"),
    COSMETICS("Cosmetics"),
    DINING("Dining"),
    ENTERTAINMENT("Entertainment"),
    EDUCATION("Education"),
    FAMILY_FRIEND("Family&Friend"),
    FINE("Fine"),
    FOOD("Food"),
    GIFTS("Gifts"),
    HEALTHCARE("Healthcare"),
    HOME("Home"),
    INVESTMENT("Investment"),
    LENDING("Lending"),
    RENT("Rent"),
    SHOPPING("Shopping"),
    TRANSPORT("Transport"),
    TRAVEL("Travel"),
    GIVE_AWAY("Give-away"),
    SAVING("Saving"),
    TAXES("Taxes"),
}